CREATE TABLE cgc_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    email  text NOT NULL UNIQUE,
    password TEXT NOT NULL,
    bio text,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
  date_modified TIMESTAMP
);